model_config:
  - model: MultiLayerPerceptron
  - model: MultiLayerPerceptronV2
    extra_args:
      learning_rate: 0.001
      use_scheduler: True
      use_early_stop: True
      early_stop_patience: 20
      clip_grad: True
      clip_grad_norm: 1.0
  # - model: Transformer
  # - model: RandomForest
  # - model: SupportVector
  # - model: KNeighbors

device: cpu
log_experiments: False
epochs: 100
subset:
  - 0.9
circuits:
  - CSVA
  - CVA
  - TSVA
  - LNA
  - Mixer
  - VCO
  - PA
  - Transmitter
  - Receiver
compare_method: True
kfold: False
independent_kfold: True
save_format: csv
save_model: True

